stages:
- build
- deploy

build:api:
  stage: build
  only:
  - docs-api
  image: php:7.1-cli
  script:
  - cd api/
  - curl -O http://get.sensiolabs.org/sami.phar
  - apt-get update -y && apt-get install git-core -y
  - git clone ${CI_REPOSITORY_URL} menu
  - php sami.phar update config.php
  - mv build ../php-api
  artifacts:
    expire_in: 1 hour
    paths:
    - php-api/

pages:
  only:
  - docs-api
  stage: deploy
  image: alpine
  script:
  - mv php-api public
  artifacts:
    expire_in: 1 hour
    paths:
    - public/

