stages:
- build
- deploy

build:docs:
  stage: build
  only:
  - docs-api
  image: ruby
  script:
  - cd docs/
  - apt-get install nodejs -y
  - gem install bundler
  - bundle install
  - bundle exec middleman build --clean
  - mv build ../ruby-docs
  artifacts:
    paths:
    - ruby-docs/

build:api:
  stage: build
  only:
  - docs-api
  image: php:7.1-cli
  script:
  - cd api/
  - curl -O http://get.sensiolabs.org/sami.phar
  - apt-get install git -y
  - git clone ${CI_REPOSITORY_URL} menu
  - php sami.phar config.php
  - mv build ../php-api
  artifacts:
    paths:
    - php-api/

pages:
  only:
  - docs-api
  stage: deploy
  image: alpine
  script:
  - mkdir public
  - mv php-api public/api
  - mv ruby-docs public/docs
  - mv index.html public/index.html
  artifacts:
    paths:
    - public/

