<?php
/**
 *
 * This file is part of vynatu/menu.
 *
 * (c) 2017 Vynatu Cyberlabs, Inc. <felix@vynatu.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Vynatu\Menu\Console;

use Illuminate\Console\GeneratorCommand;

class MakeMenuCommand extends GeneratorCommand
{

    protected $signature = 'make:menu {name}';

    protected $description = 'Creates a menu class';

    protected $type = 'Menu';

    /**
     * Get the stub file for the generator.
     *
     * @return string
     */
    protected function getStub()
    {
        return __DIR__ . '/stubs/menu.stub';
    }

    public function fire()
    {
        return parent::fire(); // TODO: Change the autogenerated stub
    }

    protected function getDefaultNamespace($rootNamespace)
    {
        return $rootNamespace.'\Menus';
    }

    protected function getOptions()
    {
        return ['extend', 'e', InputOption::VALUE_NONE, 'Generate an extender menu class.'];
    }
}